const pieces={p:'♟',r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',P:'♙',R:'♖',N:'♘',B:'♗',Q:'♕',K:'♔'};
let gameId, selected=null, current;
function position(fen){ const out=[]; for(const row of fen.split(' ')[0].split('/')){ for(const c of row){ if(/[1-8]/.test(c)) for(let i=0;i<Number(c);i++) out.push(''); else out.push(c); } } return out; }
function squareName(i){ return 'abcdefgh'[i%8]+(8-Math.floor(i/8)); }
function draw(state){ current=state; const board=document.querySelector('#board'); board.innerHTML=''; position(state.fen).forEach((piece,i)=>{ const b=document.createElement('button'); b.className='square '+((Math.floor(i/8)+i)%2?'dark':''); if(selected===i)b.classList.add('selected'); b.textContent=pieces[piece]||''; b.onclick=()=>clickSquare(i,piece); board.appendChild(b); }); }
async function clickSquare(i,piece){ if(selected===null){ if(!piece)return; selected=i; draw(current); return; } const move=squareName(selected)+squareName(i); selected=null; const response=await fetch(`/api/games/${gameId}/moves`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({move})}); const body=await response.json(); document.querySelector('#message').textContent=response.ok?`Committed ${move}`:(body.error||'Move failed'); if(response.ok){draw(body.game); renderControl(body.control);} }
function renderControl(control){ document.querySelector('#game-id').textContent=control.gameId; document.querySelector('#owner').textContent=control.ownerId||'waiting'; document.querySelector('#epoch').textContent=control.epoch; document.querySelector('#sequence').textContent=control.snapshotSeq; document.querySelector('#lease').textContent=new Date(control.leaseUntil).toLocaleTimeString(); }
async function refresh(){ if(!gameId)return; const response=await fetch(`/api/games/${gameId}`); if(response.ok){const body=await response.json();draw(body.game);renderControl(body.control);} }
(async()=>{ const response=await fetch('/api/games',{method:'POST'}); const body=await response.json(); if(!response.ok){document.querySelector('#message').textContent=body.error;return;} gameId=body.control.gameId; draw(body.game); renderControl(body.control); document.querySelector('#message').textContent='Room ready'; setInterval(refresh,1000); })();
